export { useStateContext } from '../Contexts/ContextProvider'

export { default as usePageTitle } from '../Hooks/Universal/Page_Title'
export { default as useBodyAddClass } from '../Hooks/Universal/Body_Class'
export { default as useScreenWidth } from '../Hooks/Universal/Screen_Width'

export { default as useAuthentication } from '../Hooks/Users/Authentication'
export { default as useCreateUser } from '../Hooks/Users/Create_User'
export { default as useRetrieveEmailUser } from '../Hooks/Users/Retrieve_Email_User'
export { default as useUpdatePassUser } from '../Hooks/Users/Update_Pass_User'

export { default as useRetrieveMenuList } from '../Hooks/Ordering/Retrieve_Menu_List'
export { default as useCreateOrders } from '../Hooks/Ordering/Create_Orders'
export { default as useOCRReceipt } from '../Hooks/Ordering/OCR_GCash_Receipt'

export { default as useRetrieveOrdersList } from '../Hooks/Ordering/Retrieve_Orders_List'
export { default as useUpdateOrders } from '../Hooks/Ordering/Update_Orders'

export { default as useFetchProduct } from '../Hooks/service/fetchProducts'
export { default as useCreateOrder } from '../Hooks/orders/createOrderCustomer'
export { default as useCreateReservation } from '../Hooks/customer/reservation/createReservation'
export { default as useFetchOrder } from '../Hooks/Universal/fetchProducts'


export { default as useClockText } from '../Hooks/UI Display/Clock_Text'
export { default as useDateFormat } from '../Hooks/UI Display/Date_Fetch_Format'
export { default as useTimeFormat } from '../Hooks/UI Display/Time_Fetch_Format'
export { default as useDateTimeFormat } from '../Hooks/UI Display/DateTime_Fetch_Format'



export { default as useReservationFunctions } from '../Hooks/customer/profile/Reservation_Function'
export { default as TopCategory } from '../Hooks/graphs/Top_Category'
export { default as SalesReport } from '../Hooks/graphs/Sales_Report'
export { default as useFetchOrders } from '../Hooks/orders/fetchOrder'
export { default as useKpi } from '../Hooks/Universal/Kpi'
export { default as useModifyOrderList } from '../Hooks/orders/modifyOrderList'
export { default as useFetchDashboardData } from '../Hooks/admin/fetchData'
export { default as DailyOrdersGraphs } from '../Hooks/graphs/Daily_Orders_Graphs'
export { default as useOrderHistory } from '../Hooks/admin/OrderHistory/OrderHistory'
export { default as useAttendanceStaff } from '../Hooks/service/attendance'
export { default as useModifyData } from '../Hooks/customer/profile/modifyData'
export { default as ServiceSalesReport } from '../Hooks/graphs/Service_Sales_Report'
export { default as AttendanceChart } from '../Hooks/graphs/Attendance_Chart'
export { default as useFetchUserRes } from '../Hooks/customer/reservation/fetchUserRes'
export { default as useExportCSV } from '../Hooks/Universal/fileExporter'
export { default as useFetchData } from '../Hooks/admin/fetchData'
export { default as useFetchTicketsForAI } from '../Hooks/AI/fetchTicketsForAI'
export { default as useFetchModelPrediction } from '../Hooks/AI/Fetch_Model_Prediction'
export { default as DemandForecast } from '../Hooks/graphs/Demand_Forecast_Chart'
export { default as useAddCategory } from '../Hooks/add'
export { default as useAddProduct } from '../Hooks/admin/Menu/addProduct'
export { default as useFetchInvData } from '../Hooks/admin/inv/fetchData'
export { default as useModifyItem } from '../Hooks/admin/inv/modifyItem'
export { default as useAttendanceStatusAdmin } from '../Hooks/admin/employee/attendanceStatus'
export { default as useModifyEmployee } from '../Hooks/admin/employee/modifyEmployee'
export { default as useFetchEmployees } from '../Hooks/service/fetchData'
export { default as useModifyCustomer } from '../Hooks/admin/customer_management/modifyCustomer'
export { default as useFetchCustomers } from '../Hooks/admin/customer_management/fetchCustomers'
export { default as useStockLogs } from '../Hooks/admin/activity_logs/activityLogs'