export { default as Logo } from '/Brand-Logo/LOGO.svg'
export { default as TextLogo } from '/Brand-Logo/TEXT LOGO.svg'
export { default as M7Logo } from '/Brand-Logo/M7 LOGO.svg'

export { default as FBLogo } from '/Icons/footer/FB LOGO.png'
export { default as XLogo } from '/Icons/footer/X LOGO.png'
export { default as IGLogo } from '/Icons/footer/IG LOGO.png'
export { default as PhoneLogo } from '/Icons/footer/PHONE LOGO.png'
export { default as LocationLogo } from '/Icons/footer/LOC LOGO.png'

export { default as LogoutLogo } from '/Icons/sidebar/LOGOUT LOGO.png'
export { default as DashboardLogo } from '/Icons/sidebar/DASHBOARD LOGO.png'
export { default as OrderlistLogo } from '/Icons/sidebar/ORDERLIST LOGO.png'
export { default as ProfileLogo } from '/Icons/sidebar/PROFILE LOGO.png'
export { default as SalesLogo } from '/Icons/sidebar/SALES LOGO.png'
export { default as InventoryLogo } from '/Icons/sidebar/INVENTORY LOGO.png'
export { default as EmployeeLogo } from '/Icons/sidebar/EMPLOYEE LOGO.png'
export { default as CustomerLogo } from '/Icons/sidebar/CUSTOMER LOGO.png'

export { default as ViewLogo } from '/Icons/table/VIEW LOGO.png'
export { default as EditLogo } from '/Icons/table/EDIT LOGO.png'
export { default as DeleteLogo } from '/Icons/table/DELETE LOGO.png'