export { default as LOGO } from '/img/LOGO.png'
export { default as TEXTLOGO } from '/img/TEXT LOGO.png'
export { default as M7LOGO } from '/img/M7 LOGO.png'
export { default as FBLOGO } from '/img/FOOTER FB LOGO.png'
export { default as XLOGO } from '/img/FOOTER X LOGO.png'
export { default as IGLOGO } from '/img/FOOTER IG LOGO.png'
export { default as PHONELOGO } from '/img/FOOTER PHONE LOGO.png'
export { default as LOCLOGO } from '/img/FOOTER LOC LOGO.png'

export { default as LOGOUTLOGO } from '/sidebars/LOGOUT LOGO.png'
export { default as DASHBOARDLOGO } from '/sidebars/DASHBOARD LOGO.png'
export { default as ORDERLISTLOGO } from '/sidebars/ORDERLIST LOGO.png'
export { default as PROFILELOGO } from '/sidebars/PROFILE LOGO.png'
export { default as SALESLOGO } from '/sidebars/SALES LOGO.png'
export { default as INVENTORYLOGO } from '/sidebars/INVENTORY LOGO.png'
export { default as EMPLOYEELOGO } from '/sidebars/EMPLOYEE LOGO.png'
export { default as CUSTOMERLOGO } from '/sidebars/CUSTOMER LOGO.png'

export { default as EDITLOGO } from '/table/EDIT LOGO.png'
export { default as VIEWLOGO } from '/table/VIEW LOGO.png'
export { default as DELETELOGO } from '/table/DELETE LOGO.png'